name: iv_dashboard_project_web_app
description: "In Vite Dashboard Project App."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  iv_project_model:
    path: ../iv_project_model

  iv_project_web_data:
    path: ../iv_project_web_data

  iv_project_core:
    path: ../iv_project_core

  iv_project_widget_core:
    path: ../iv_project_widget_core

  quick_dev_sdk:
    path: ../quick_dev_sdk

  go_router: ^17.0.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  file_saver: ^0.3.1
  file_picker: ^10.3.6
  excel: ^4.0.6
  url_launcher: ^6.3.2
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/templates/formulir_tamu_undangan.xlsx
